params:
  epochs: 20
  batch_size: 32
  num_classes: 10
  loss_function: sparse_categorical_crossentropy
  metrics: accuracy
  optimizer: adam
  size: 5000

artifacts:
  artifacts_dir: artifacts
  model_dir: model
  plots_dir: plots
  checkpoints_dir: checkpoints
  model_name: model.h5

logs:
  logs_dir: logs
  general_logs: general_logs
  tensorboard_logs: tensorboard_logs

